Update copy in experiences
Trustroots/trustroots pull request #2135
Opened 2021-03-07 00:18 UTC by simison

#### Proposed Changes

* Add "Based on your experience, ..." in recommendation questions
* Change "I don't know" to "skip" in recommendation question
* Always show "It's extremely important you report anyone behaving against rules to us." instead of showing it only when people choose "no"
* Correct typo under feedback field

#### Testing Instructions

* Write experience, and observe steps work

![image](https://user-images.githubusercontent.com/87168/110225159-41b92880-7eeb-11eb-8f9e-70180fcabac5.png)
![image](https://user-images.githubusercontent.com/87168/110225161-4847a000-7eeb-11eb-8238-5001195bdf59.png)
<img width="877" alt="Screenshot 2021-03-07 at 01 53 39" src="https://user-images.githubusercontent.com/87168/110225164-4da4ea80-7eeb-11eb-9ce9-b6640a8e5314.png">

2021-03-07 00:19 UTC, simison commented on modules/experiences/client/components/create-experience/Feedback.js
> +            'The answer you write will be publicly available on their profile.',
Just a typo correction here:

<img width="877" alt="Screenshot 2021-03-07 at 01 53 39" src="https://user-images.githubusercontent.com/87168/110225164-4da4ea80-7eeb-11eb-9ce9-b6640a8e5314.png">

2021-03-07 10:37 UTC, hlibbabii commented
I like "Skip" much better than "I don't know"! Maybe make it grey?

2021-03-07 10:44 UTC, simison commented
Thanks @hlibbabii ! I tried but I disliked how it became less obvious it's actionable. We also have a lot of different styles for "click me" type things (even in just this one view) so I'd like to try limit adding more. 😅 

 
<img width="1110" alt="Screenshot 2021-03-07 at 12 40 58" src="https://user-images.githubusercontent.com/87168/110237143-ce430580-7f42-11eb-9284-b03b993dae7c.png">

Your sentiment might've been "can it be separated a bit from the other two", for which I tried this — what do you think?

<img width="822" alt="Screenshot 2021-03-07 at 12 42 55" src="https://user-images.githubusercontent.com/87168/110237149-d9963100-7f42-11eb-9cf5-92f49e2d25b4.png">

Simple empty space goes long way, too:

<img width="816" alt="image" src="https://user-images.githubusercontent.com/87168/110237156-e581f300-7f42-11eb-8ab1-5eeb4ad92b46.png">

2021-03-07 11:15 UTC, simison commented
As a side note, those 3-step-styles have regressed at some point and need tweaking. Active tab shouldn't look like a button.

They were clickable at some point but looks like no longer.

2021-03-07 14:11 UTC, hlibbabii commented
> Your sentiment might've been "can it be separated a bit from the other two",

exactly! 

Yeah, I think some visual separation would be nice, and your suggestions are good, I am thinking about it but still not sure what's the best

2021-03-07 15:01 UTC, simison commented
I'll add the line so that we get to play and feel it little bit.

2021-03-08 09:00 UTC, noahsmindfuck requested changes
I am not sure. I like the "Based on your experience" thing, generally, but wasn't it that we would rather ask them:
"Besides your personal experience, would you still recommend others to host them?" or
"Would you recommend <username> to others, independent from your personal experience with them?

The feeling that I have is that we - with my version of the question - support to not rate a person just on one experience and to make the experience less about the other. This way we are already starting to make the experience about us and we recommend the other person unrelated to our experience.

With the question of @simison we are doing the opposite and we create an environment where the single experience with a person is dominating over the public persona of the other. I do not refer to abuse of the experience system here, I mean that it even happens subconsciously and that I would prefer not to create a place where we are rating members. :)

I very much like the seperation with a | for the I don't know and I very much agree on @simison for the styling of the tabs.

2021-03-09 10:55 UTC, simison commented
@noahsmindfuck yasss I agree with those copy suggestions — I was hoping someone could chime in with more specific suggestion than what I could remember from the call. :-)

> "Besides your personal experience, would you still recommend others to host them?"

This sounds clear 👍

2021-03-14 08:35 UTC, simison commented
Updated copy based on @noahsmindfuck 's feedback as well added small changes suggested by @MrSalami at https://github.com/Trustroots/trustroots/pull/2148

2021-03-14 09:21 UTC, merged

2021-03-14 12:28 UTC, noahsmindfuck commented
Maybe change it to
>It is very important for us that you report anyone who breaks the [https://www.trustroots.org/rules rules]!

2021-03-14 12:43 UTC, simison commented
@noahsmindfuck I did want to, but at the same time I don't want to make it unclear what happens by clicking links while filling in this form. Needs a modal methinks.

2021-03-14 16:25 UTC, noahsmindfuck commented
@simison we could add the "opens in new tab" thingy symbol. I think its quite a convention to link to the thing that you mention ant that ppl know that but I might be wrong.

2021-03-14 17:23 UTC, simison commented
Yep, I think we could try how that feels.